### ISSUE TITLE
SFDX: Retreive Manifest from Org keeps on running Endlessly

### ISSUE THREAD

**Issue by HarshPreeti** [aojedo/sfdx-retrieve#3]
1.Create a Project with Manifest
2. Authorize Salesforce Org.
3.Manifest>>Pacakage.xml>>SFDX:Retrieve Manifest From Org
4.It doesn't retrive anything just keeps running, no errors.

**Comment by aojedo** [comment]
There must be an issue on your SFDX setup...
This command just types in your console the SFDX commands for retrieving a category of metadata.

I just tested it and so far it's working:
![Captura de pantalla 2021-04-07 a las 9 03 25](https://user-images.githubusercontent.com/55832466/113824620-4c800b00-9780-11eb-97a6-582d5d1dfe83.png)

Have a look at the SFDX Retrieve Terminal after executing to check for possible errors in your console.
